name:                adventofcode
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/jvanbruegge/adventofcode#readme
license:             MIT
author:              Jan van Brügge
maintainer:          jan@vanbruegge.de
copyright:           2019 Jan van Brügge
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - vector
  - text
  - mtl

executables:
  adventofcode:
    source-dirs:      src
    main:             Main.hs
